SENDGRID_USERNAME:
SENDGRID_PASSWORD:
SECRET_KEY_BASE:
STRIPE_PUBISHABLE_KEY:
STRIPE_SECRET_KEY:

development:
  secret_key_base:
  STRIPE_PUBLISHABLE_KEY:
  STRIPE_SECRET_KEY: 

test:
  secret_key_base:
